### PR TITLE
Fix modal content overflow

### PR DESCRIPTION
**Pull request by chowington**
Warning: not extensively tested! 😅

### CODE REVIEW

**Review by jernestmyers — APPROVED** [review]
Looks okay to me when testing in the subsetting download modal. Not sure where else to "test" wherein the modal content becomes scrollable?

**Comment by asizemore** [comment]
@jernestmyers or @chowington are either of you on linux? I'm curious if the changes here may reintroduce some issues people found a while back with the modal styling ([slack message](https://epvb.slack.com/archives/C02R14DUYLX/p1643986183571299)).
I'm only concerned because i noticed that the changes in this PR revert some of the changes from [this commit](https://github.com/VEuPathDB/CoreUI/commit/b0cd1d285b33591d82c0d01af8619ceb9da61c80) that fixed some browser compatibility styling issues.

I'm on a mac and things are looking good here btw!

**Comment by asizemore** [comment]
@jernestmyers or @chowington are either of you on linux? I'm curious if the changes here may reintroduce some issues people found a while back with the modal styling ([slack message](https://epvb.slack.com/archives/C02R14DUYLX/p1643986183571299)).
I'm only concerned because i noticed that the changes in this PR revert some of the changes from [this commit](https://github.com/VEuPathDB/CoreUI/commit/b0cd1d285b33591d82c0d01af8619ceb9da61c80) that fixed some browser compatibility styling issues.

I'm on a mac and things are looking good here btw!

**Comment by chowington** [comment]
I prefer living with 2

**Comment by jernestmyers** [comment]
I vote option 2. Much more subtle.

**Comment by asizemore** [comment]
i vote for 2 as well!

**Pull request merged**
