### PR TITLE
Banner timeout

### PR DESCRIPTION
**Pull request by moontrip**
Following the recommendation by Bob to add a timeout feature, it was implemented

### CODE REVIEW

**Review by chowington — CHANGES_REQUESTED** [review]
This all looks good! My only request is just a preference, but what do you think about adding a fade-out effect when the message disappears? It would be a little less jarring with that, I think.

**Comment by moontrip** [comment]
@chowington thank you for your review and comment. Yes it would be nice to have. I will think about that sooner or later after another work being in progress 👍

**Comment by chowington** [comment]
Cool, and since we're not using the amazing, astounding disappearing banner yet, I'll go ahead and fully approve!

**Review by chowington — APPROVED** [review]

**Comment by moontrip** [comment]
@chowington Thank you for your approval! 👍 By the way, I made a fadeout so it would be great if you can re-review this. You can test it at story.

**Review by chowington — APPROVED** [review]
Looks good, thanks for the fadeout effect!

**Comment by moontrip** [comment]
@chowington Thank you for your review and tests 👍 🥳

**Pull request merged**
